os: linux
language: node_js
node_js:
- 12
before_script:
- npm i
script:
- npm run build
- npm test
deploy:
  provider: npm
  email: hokkey@gmail.com
  on:
    tags: true
    branch: master
  api_key:
    secure: KwMpHE7Kj4VfWLlHlLm/KfDWc1u4Zo0Qt3h15XMnvXhcxcPno0ry0UsnVdkAf2PZolV2Kz0k7pyyliF/0tKXqTo9VSN8fOYotzyTTIrAbmZQb3NECwxUfMfj/Udj82JrsOE0is+NUVziefFfSYSLXEXg5xR+a9LeAq442KD3eoPDZ7q1iSQQhFRQixxm3Y9MQVLVoL5RajJkDebrHUhc6VxHnMsq9HThfG8rnPV9Y3gBaTU6bcFlpGOKJ5yyP71ZYVmk2LbWUFn8m5rJWxjQSsvLuEwAoD32fvQdCdqAtYbflBmnSfsxG34gWYqPmu3svHXG7Cgf5OEyCYLfyIlijPsKYLlipxgxnTbQHElmWwGh6gDxEIXKRQTm9cIpJz+WI7UAuDb2HXoPUdsGezAEGZD4VtuPM90Bz0w5vJZZOIhqqopdU199dSB++LOnTIp6c1gwRTT4HSsO4IbnhXB5nK0JaD9qLXw+pb5NxSEbHUXRb1qVg55QsbEnn4JNAYkZDKEwjIstXwxC11u1bHW7u6MDCUxKDgd/vwOnn4mW/RPATBfTCV09Qsxxm8ezIsaimcP2WYArW0MZ87WQNV4ioZxs8bScQUjSdJ3uByco2giTV+D9fYGZb7BNMIQ5CqHP6zItvUwBWNWLqSerrHSE6wghA7elWyQf/oWDvnsqBHU=
